package com.example.soyamgebeya.service

import com.example.BuildConfig
import com.squareup.moshi.JsonClass
import okhttp3.OkHttpClient
import retrofit2.Retrofit
import retrofit2.converter.moshi.MoshiConverterFactory
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query
import java.util.concurrent.TimeUnit
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext

@JsonClass(generateAdapter = true)
data class GeminiPart(val text: String)

@JsonClass(generateAdapter = true)
data class GeminiContent(val parts: List<GeminiPart>)

@JsonClass(generateAdapter = true)
data class GeminiRequest(
    val contents: List<GeminiContent>,
    val systemInstruction: GeminiContent? = null
)

@JsonClass(generateAdapter = true)
data class GeminiCandidate(val content: GeminiContent?)

@JsonClass(generateAdapter = true)
data class GeminiResponse(val candidates: List<GeminiCandidate>?)

interface GeminiApi {
    @POST("v1beta/models/gemini-3.5-flash:generateContent")
    suspend fun generateContent(
        @Query("key") apiKey: String,
        @Body request: GeminiRequest
    ): GeminiResponse
}

object GeminiService {
    private const val BASE_URL = "https://generativelanguage.googleapis.com/"

    private val okHttpClient = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .client(okHttpClient)
        .addConverterFactory(MoshiConverterFactory.create())
        .build()

    private val api: GeminiApi by lazy {
        retrofit.create(GeminiApi::class.java)
    }

    suspend fun generateResponse(prompt: String, systemPrompt: String? = null): String = withContext(Dispatchers.IO) {
        val apiKey = BuildConfig.GEMINI_API_KEY
        if (apiKey.isEmpty() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext "API Configuration Needed: Please configure your GEMINI_API_KEY in the AI Studio environment or Secrets panel to activate full AI assistance. (Running in demo mode)."
        }

        val request = GeminiRequest(
            contents = listOf(GeminiContent(parts = listOf(GeminiPart(prompt)))),
            systemInstruction = systemPrompt?.let { GeminiContent(parts = listOf(GeminiPart(it))) }
        )

        try {
            val response = api.generateContent(apiKey, request)
            response.candidates?.firstOrNull()?.content?.parts?.firstOrNull()?.text ?: "No response generated by AI."
        } catch (e: Exception) {
            "AI Assistant (Offline Simulation): ${getDemoResponse(prompt, systemPrompt)}"
        }
    }

    private fun getDemoResponse(prompt: String, systemPrompt: String?): String {
        val query = prompt.lowercase()
        return when {
            systemPrompt != null && systemPrompt.contains("advisor") -> {
                "**Soyam Business Advisor Recommendations:**\n\n💰 **Pricing Strategy**: Your item seems competitively placed. In Addis Ababa markets, high-end electronics see a 5% price premium on Bole road sales. Consider listing at 28,000 ETB for quick turnover.\n\n📈 **Visibility Tips**:\n1. Translate your description to Amharic and Afaan Oromo to double your target audience size!\n2. Opt-in for our Telebirr cashback reward integration to acquire 2.5x more click-throughs.\n3. Verify your trade credentials for a 'Verified Seller' badge."
            }
            query.contains("telebirr") || query.contains("payment") || query.contains("cbe") -> {
                "**Soyam Payment Assistant:** Soyam Gebeya is fully integrated with **Telebirr**, **CBEBirr**, and **Chapa**. To pay, simply tap 'Buy with Telebirr', enter your passcode in the secure popup overlay, and the funds are escrowed safely until delivery! You will earn **Soyam Reward Points** (2% cashback) on this transaction."
            }
            query.contains("hello") || query.contains("hi") || query.contains("ስላም") -> {
                "Selam! Welcome to Soyam Gebeya (everything market). I am your smart AI marketplace guide. I can translate listings, suggest local pricing trends in Birr, locate items near Bole or Mercato, and assist you in becoming a verified merchant. How can I help you today?"
            }
            query.contains("price") || query.contains("cost") || query.contains("birr") -> {
                "Based on recent Bole, Mercato, and Hawassa commerce listings on Soyam Gebeya:\n- Phones range from 12,000 ETB to 90,000 ETB.\n- Services (plumbers/electricians) range from 500 ETB to 3000 ETB.\n\nTip: You can use the 'AI Pricing Tool' inside the Sell screen to get exact estimations based on current local demands!"
            }
            else -> {
                "Welcome to Ethiopia's premier super app, Soyam Gebeya! How can I help you navigate through listings of products, services, agricultural equipment, apartments, jobs, or assist with Telebirr transfers?"
            }
        }
    }
}
